nmHoistingLimits: dependencies

nodeLinker: pnp

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  vite@*:
    dependencies:
      supports-color: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

pnpMode: loose

npmPublishAccess: "public"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
