compressionLevel: mixed

enableGlobalCache: false

nmHoistingLimits: dependencies

nodeLinker: pnp

npmPublishAccess: public

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  vite@*:
    dependencies:
      supports-color: "*"

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.5.0.cjs
